## N-GRAM

In [36]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
# n=1 / n=2 / n=3
class NGramModelLanguage:
    def __init__(self, n):
        self.n=n
        self.vectorizer = CountVectorizer(analyzer='word', ngram_range=(n,n))
        
    def fit_transform(self,corpus):
        return self.vectorizer.fit_transform(corpus)
    
    def transform(self,corpus):
        return self.vectorizer.transform(corpus)

In [38]:
def calculate_cosine_similarity(target, query):
    similarity = cosine_similarity(target, query)
    return similarity

In [39]:
target = [
    "i love machine learning",
    "natural language processing is fun",
    "i enjoy learning new models",
    "text data is interesting",
    "ngrams help capture patterns"
]

query = ["language models are fun"]

n = 1

In [40]:
n_gramModel = NGramModelLanguage(n)

target_vector = n_gramModel.fit_transform(target)
query_vector = n_gramModel.transform(query)

In [41]:
pd.DataFrame(target_vector.toarray(), columns=n_gramModel.vectorizer.get_feature_names_out())

,capture,data,enjoy,fun,help,interesting,is,language,learning,love,machine,models,natural,new,ngrams,patterns,processing,text
0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0
1,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,1,0
2,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0
3,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1
4,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0

In [42]:
similarity = calculate_cosine_similarity(target_vector, query_vector)
data={
    'document':target,
    'similarity':similarity.flat
}

df = pd.DataFrame(data)
df

                             document  similarity
0             i love machine learning    0.000000
1  natural language processing is fun    0.516398
2         i enjoy learning new models    0.288675
3            text data is interesting    0.000000
4        ngrams help capture patterns    0.000000

In [43]:
def calculate_cosine_similarity(corpus2, query2):
    similarity2 = cosine_similarity(corpus2, query2)
    return similarity2

In [44]:
target2 = [
    'Try to Learning',
    'Natural Language Processing',
    'In Software Laboratory Class'
]

query2 = ['Try Query the Natural Language Processing Corpus']

n=2

In [46]:
n_gramModel = NGramModelLanguage(n)

target_vector2 = n_gramModel.fit_transform(target2)
query_vector2 = n_gramModel.transform(query2)

In [ ]:
pd.DataFrame(target_vector2.toarray(), columns=n_gramModel)